# Generated by Django 5.0.6 on 2026-05-04 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=5)),
                ('frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('biweekly', 'Bimensuel'), ('monthly', 'Mensuel')], default='monthly', max_length=10)),
                ('start_date', models.DateField()),
                ('max_members', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Active'), ('completed', 'Terminée'), ('paused', 'En pause')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tontines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TontineMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tontine.tontine')),
            ],
            options={
                'ordering': ['position', 'joined_at'],
                'unique_together': {('tontine', 'member')},
            },
        ),
        migrations.AddField(
            model_name='tontine',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='tontines', through='tontine.TontineMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TontineRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Active'), ('completed', 'Terminée')], default='pending', max_length=10)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tontine_rounds_received', to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tontine.tontine')),
            ],
            options={
                'ordering': ['round_number'],
                'unique_together': {('tontine', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='TontineContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='tontine/proofs/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tontine_contributions', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='tontine.tontineround')),
            ],
            options={
                'ordering': ['-paid_at'],
                'unique_together': {('round', 'contributor')},
            },
        ),
    ]
