# Generated by Django 5.0.6 on 2026-05-04 00:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolidarityFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='EUR', max_length=5)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('medical', 'Médical'), ('education', 'Éducation'), ('emergency', 'Urgence'), ('repatriation', 'Rapatriement'), ('funeral', 'Obsèques'), ('other', 'Autre')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='active', max_length=15)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='solidarity/covers/')),
                ('beneficiary_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_funds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolidarityContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('message', models.CharField(blank=True, max_length=500)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('contributed_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solidarity_contributions', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='solidarity.solidarityfund')),
            ],
            options={
                'ordering': ['-contributed_at'],
            },
        ),
    ]
